SHOW DATABASES;
USE OFICINA;

-- TABELAS PRINCIPAIS

CREATE TABLE CLIENTS (
	IDCLIENT INT PRIMARY KEY AUTO_INCREMENT,
    FNAME VARCHAR (20) NOT NULL,
    LNAME VARCHAR (20) NOT NULL,
    IDENTIFICATION ENUM ('PF','PJ'),
    CPF CHAR (11),
    CNPJ VARCHAR (15),
    ADDRESS VARCHAR (255),
    CONSTRAINT UNIQUE_CPF_CLIENTS UNIQUE (CPF),
    CONSTRAINT UNIQUE_CNPJ_CLIENTS UNIQUE (CNPJ)
);
CREATE TABLE ORDERS(
	IDORDER INT AUTO_INCREMENT PRIMARY KEY,
    IDORDERCLIENT INT,
    STARTDATE DATE,
    ENDDATE DATE,
    STATUSORDER ENUM ('ABERTO','APROVADO','CANCELADO') DEFAULT 'ABERTO',
    CONSTRAINT FK_ORDERCLIENT FOREIGN KEY (IDORDERCLIENT) REFERENCES CLIENTS (IDCLIENT)
);
CREATE TABLE SERVICEORDERS(
	IDSERVICEORDER INT AUTO_INCREMENT PRIMARY KEY,
    IDSERVICEORDERORDER INT,
    STARTDATE DATE NOT NULL,
    ENDDATE DATE,
    STATUSSERVICEORDER ENUM ('EM PROCESSAMENTO','FINALIZADO','CANCELADO') DEFAULT 'EM PROCESSAMENTO',
    CONSTRAINT FK_SERVICE_ORDER_ORDER FOREIGN KEY (IDSERVICEORDERORDER) REFERENCES ORDERS (IDORDER)
);
CREATE TABLE SERVICETYPE(
	IDSERVICETYPE INT AUTO_INCREMENT PRIMARY KEY,
    SERVICENAME VARCHAR (20) NOT NULL,
    SERVICEDESCRIPTION VARCHAR (255) NOT NULL,
    SERVICECATEGORY VARCHAR (50) NOT NULL,
    SERVICEVALUEHOUR FLOAT NOT NULL
);
CREATE TABLE PARTS(
	IDPARTS INT AUTO_INCREMENT PRIMARY KEY,
    PARTNAME VARCHAR (20) NOT NULL,
    PARTDESCRIPTION VARCHAR (20) NOT NULL,
    PARTCATEGORY VARCHAR (50) NOT NULL,
    PARTVALUEUNITARY FLOAT NOT NULL
);
CREATE TABLE MECHANIC(
	IDMECHANIC INT AUTO_INCREMENT PRIMARY KEY,
    MECHANICFNAME VARCHAR (20) NOT NULL,
    MECHANICLNAME VARCHAR (20) NOT NULL,
    MECHANICCPF CHAR (11) NOT NULL,
    MECHANICCATEGORY VARCHAR (50) NOT NULL
);
CREATE TABLE WAREHOUSE(
	IDWAREHOUSE INT AUTO_INCREMENT PRIMARY KEY,
    PARTNAMEWAREHOUSE VARCHAR (20) NOT NULL,
    QUANTITY INT DEFAULT(0)
);

-- TABELAS DERIVADAS

CREATE TABLE SERVICEVALUE(
	IDSERVICEVALUE INT NOT NULL,
    IDSERVICEVALUEORDER INT NOT NULL,
    SERVICEVALUETOTAL FLOAT DEFAULT (0),
    SERVICEHOURTOTAL INT DEFAULT (0),
    CONSTRAINT FK_SERVICE_VALUE FOREIGN KEY (IDSERVICEVALUE) REFERENCES SERVICETYPE (IDSERVICETYPE),
    CONSTRAINT FK_SERVICE_VALUE_ORDER FOREIGN KEY (IDSERVICEVALUEORDER) REFERENCES ORDERS (IDORDER)
);
CREATE TABLE PARTSVALUE(
	IDPARTVALUE INT NOT NULL,
    IDPARTVALUEORDER INT NOT NULL,
    PARTVALUETOTAL FLOAT DEFAULT (0),
    QUANTITY INT DEFAULT (1),
    CONSTRAINT FK_PART_VALUE FOREIGN KEY (IDPARTVALUE) REFERENCES PARTS (IDPARTS),
    CONSTRAINT FK_PART_VALUE_ORDER FOREIGN KEY (IDPARTVALUEORDER) REFERENCES ORDERS (IDORDER)
);
CREATE TABLE PARTSWAREHOUSE(
	IDPARTWAREHOUSE INT NOT NULL,
    IDPARTWAREHOUSEWAREHOUSE INT NOT NULL,
    QUANTITY INT,
    CONSTRAINT FK_PART_WAREHOUSE FOREIGN KEY (IDPARTWAREHOUSE) REFERENCES PARTS (IDPARTS),
    CONSTRAINT FK_PART_WAREHOUSE_WAREHOUSE FOREIGN KEY (IDPARTWAREHOUSEWAREHOUSE) REFERENCES WAREHOUSE (IDWAREHOUSE)
);
CREATE TABLE SERVICEMECHANIC(
	IDSERVICEMECHANIC INT NOT NULL,
    IDSERVICEMECHANICMECHANIC INT NOT NULL,
    CONSTRAINT FK_SERVICE_MECHANIC FOREIGN KEY (IDSERVICEMECHANIC) REFERENCES SERVICETYPE (IDSERVICETYPE),
    CONSTRAINT FK_SERVICE_MECHANIC_MECHANIC FOREIGN KEY (IDSERVICEMECHANICMECHANIC) REFERENCES MECHANIC (IDMECHANIC)
);