-- CRIAÇÃO DE UM BD PARA ECOMMERCE

CREATE DATABASE ECOMMERCE;
USE ECOMMERCE;

-- TABELAS PRINCIPAIS

CREATE TABLE CLIENTS(
	IDCLIENT INT AUTO_INCREMENT PRIMARY KEY,
    FNAME VARCHAR(10) NOT NULL,
    MINIT VARCHAR(3) NOT NULL,
    LNAME VARCHAR(10) NOT  NULL,
    CPF CHAR(11) NOT NULL,
    ADDRESS VARCHAR(40) NOT NULL,
    CONSTRAINT UNIQUE_CPF_CLIENT UNIQUE (CPF)
);
CREATE TABLE PRODUCT(
	IDPRODUCT INT AUTO_INCREMENT PRIMARY KEY,
    PNAME VARCHAR(10) NOT NULL,
    CLASSIFICATION BOOL,
    CATEGORY ENUM ('ELETRÔNICO','VESTIMENTA','BRINQUEDOS','ALIMENTOS') NOT NULL,
    AVALIATION FLOAT DEFAULT 0,
    SIZE VARCHAR(10) DEFAULT 0
);
CREATE TABLE PAYMENTS(
    IDPAYMENT INT AUTO_INCREMENT PRIMARY KEY,
    TYPEPAYMENT ENUM ('CARTÃO','DOIS CARTÕES'),
    LIMITEAVAILABLE FLOAT
);
CREATE TABLE ORDERS(
	IDORDER INT AUTO_INCREMENT PRIMARY KEY, 
    IDORDERCLIENT INT,
    ORDERSTATUS ENUM('CANCELADO', 'CONFIRMADO','EM PROCESSAMENTO') DEFAULT 'EM PROCESSAMENTO',
    ORDERDESCRIPTION VARCHAR(255),
    SENDVALUE FLOAT DEFAULT 0,
    PAYMENTCASH BOOL DEFAULT FALSE, 
    IDPAYMENT INT,
    CONSTRAINT FK_ORDERS_CLIENT FOREIGN KEY (IDORDERCLIENT) REFERENCES CLIENTS(IDCLIENT)
);
CREATE TABLE PRODUCTESTORAGE(
	IDPRODSTORAGE INT AUTO_INCREMENT PRIMARY KEY,
    ESTORAGELOCATION VARCHAR(255),
    QUANTITY INT DEFAULT 0
);
CREATE TABLE SUPPLIER(
	IDSUPPLIER INT AUTO_INCREMENT PRIMARY KEY,
    SOCIALNAME VARCHAR (255) NOT NULL,
    CNPJ CHAR(15) NOT NULL,
    CONTACT CHAR(11) NOT NULL,
    CONSTRAINT UNIQUE_SUPPLIER UNIQUE(CNPJ)
);
CREATE TABLE SELLER(
	IDSELLER INT AUTO_INCREMENT PRIMARY KEY,
    SOCIALNAME VARCHAR(255) NOT NULL,
    CNPJ CHAR(15),
    CPF CHAR(9),
    LOCATION VARCHAR(255),
    CONTACT CHAR(11) NOT NULL,
    CONSTRAINT UNIQUE_CNPJ_SELLER UNIQUE (CNPJ),
    CONSTRAINT UNIQUE_CPF_SELLER UNIQUE (CPF)
);
CREATE TABLE TRACKING(
    IDTRACKING INT AUTO_INCREMENT PRIMARY KEY,
    IDORDER INT,
    TRACKINGCODE VARCHAR(50) NOT NULL,
    STATUSTRACKING ENUM ('AGUARDANDO AUTORIZAÇÃO','AGUARDANDO SEPARAÇÃO','EM PREPARAÇÃO','EM TRÂNSITO','CHEGOU AO DESTINO') DEFAULT 'AGUARDANDO AUTORIZAÇÃO',
    SHIPPEDDATE DATE,
    DELIVERYDATE DATE,
    CONSTRAINT FK_ORDER_TRACKING FOREIGN KEY (IDORDER) REFERENCES ORDERS(IDORDER),
    CONSTRAINT UNIQUE_TRACKINGCODE UNIQUE (TRACKINGCODE)
);

-- TABELAS DERIVADAS

CREATE TABLE PRODUCTSELLER(
	IDPSELLER INT,
    IDPPRODUCT INT,
    PRODUCTQUANTITY INT DEFAULT 1,
    PRIMARY KEY (IDPSELLER,IDPPRODUCT),
    CONSTRAINT FK_PRODUCT_SELLER FOREIGN KEY (IDPSELLER) REFERENCES SELLER(IDSELLER),
    CONSTRAINT FK_PRODUCT_PRODUCT FOREIGN KEY (IDPPRODUCT) REFERENCES PRODUCT(IDPRODUCT)
);
CREATE TABLE PRODUCTORDERS(
	IDPOPRODUCT INT,
    IDPOORDER INT,
    POQUANTITY INT DEFAULT 1,
    POSTATUS ENUM ('DISPONÍVEL','SEM ESTOQUE') DEFAULT 'DISPONÍVEL',
    PRIMARY KEY (IDPOPRODUCT, IDPOORDER),
    CONSTRAINT FK_PRODUCT_ORDER_SELLER FOREIGN KEY (IDPOPRODUCT) REFERENCES PRODUCT (IDPRODUCT),
    CONSTRAINT FK_PRODUCT_ORDER_PRODUCT FOREIGN KEY (IDPOORDER) REFERENCES ORDERS (IDORDER)
);
CREATE TABLE STORAGELOCATION(
	IDLPRODUCT INT,
    IDLSTORAGE INT,
    LOCATION VARCHAR(255) NOT NULL,
    PRIMARY KEY (IDLPRODUCT, IDLSTORAGE),
    CONSTRAINT FK_PRODUCT_STORAGE_SELLER FOREIGN KEY (IDLPRODUCT) REFERENCES PRODUCT (IDPRODUCT),
    CONSTRAINT FK_PRODUCT_STORAGE_PRODUCT FOREIGN KEY (IDLSTORAGE) REFERENCES PRODUCTESTORAGE(IDPRODSTORAGE)
    
);
CREATE TABLE PRODUCTSUPPLIER(
	IDPSSUPPLIER INT,
    IDPSPRODUCT INT,
    QUANTITY INT NOT NULL,
    PRIMARY KEY (IDPSSUPPLIER, IDPSPRODUCT),
    CONSTRAINT FK_PRODUCT_SUPPLIER_SUPPLIER FOREIGN KEY (IDPSSUPPLIER) REFERENCES SUPPLIER (IDSUPPLIER),
    CONSTRAINT FK_PRODUCT_SUPPLIER_PRODUCT FOREIGN KEY (IDPSPRODUCT) REFERENCES PRODUCT (IDPRODUCT)
);
CREATE TABLE PAYMENTCLIENTS(
	IDPCLIENT INT,
    IDPPAYMENT INT,
    PRIMARY KEY (IDPCLIENT, IDPPAYMENT),
    CONSTRAINT FK_PAYMENT_CLIENTS FOREIGN KEY (IDPCLIENT) REFERENCES CLIENTS(IDCLIENT),
    CONSTRAINT FK_PAYMENT_PAYMENT FOREIGN KEY (IDPPAYMENT) REFERENCES PAYMENTS(IDPAYMENT)
);